# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20160618_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
